# Generated by Django 3.0 on 2019-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(),
        ),
    ]
