# Generated by Django 3.0 on 2019-12-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addBooks', '0002_auto_20191205_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
