# Generated by Django 3.0 on 2019-12-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addBooks', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('isbn', 'user_id')},
            },
        ),
    ]
