# Generated by Django 3.0 on 2019-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBooks', '0004_bookstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('star', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('isbn', 'user_id')},
            },
        ),
    ]
