# Generated by Django 3.0 on 2019-12-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBooks', '0005_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
