# Generated by Django 3.0 on 2019-12-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addBooks', '0006_bookreview_last_modified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together=set(),
        ),
    ]
