# Generated by Django 3.0 on 2019-12-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookList', '0002_auto_20191204_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(),
        ),
    ]
